version: 1.0.{build}
image: Visual Studio 2015
clone_depth: 1
init:
- ps:
install:
- set PATH=%APPDATA%\npm;%PATH%
- npm i -g bower gulp
- npm i
- bower i
build_script:
- gulp
test_script:
- npm run test
- npm run tezt
